language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  on: master
  app: ncgrad
notifications:
  slack:
    secure: rAAOnOhmv0zkvPRHrO4MELIAvLSxx8/Mk5rTBpnY8UFUr6YXwjSYucGYfb1yVTBe82FRgK2l/rtAw/Ir3sF8FIw7aVipJexsElQ9PyQoC3Kp11iXZP4ntxG6nhsDBbWhdPj5bhgm5LywQ3bEsP9KSE/FpLrtqsnvCcMyazAf2XgKpJmy/D2CkFvMPmemvhDhX6ipnGDG92C00ANDnLS7eD+Jtic0tLAeDHRAEL/7lNTC50CLJUP7+C0BHv5so1vohbrHLJe527eHniPMLgT2q6EkWUAY+5VSTaloFxm05PMeP+eSCjYPhDw2oP+g/cBNO8cKmpRzJMEOZimMy2BIEsxcl1sIaJXETKcEuR/LmDWsfyhmVBLiawn0W7KZ92Qtv+KQy+RiEygH2QATsCmL1TVakMw8TfLAgJ5Au4+aeMUd8UjLWJp//AcAHxBjLiVxY6V7YjBnR4b7g6Gjw8/g2180nMd1E3aKrzKoZqrpCL/ThsKBrVxbGUqNVN+BPAp6eKS/02sJDrJYBz46ajVVEV/zk17oPLyj45lZkCzvzugMHXcNnjVrzpducG9q38pXdvNTCpAuIchXv3MEJcKUH7E1vuTE0qcezWSd30UR2K52YG7ryzP+zQMBjZbI6oAL4fDSbBCd40p3eDf004EMsF3HT9MtLFKiRvJHfGBT81M=
